[WIP] Mir robot env integration
motion2ai/mir_robot pull request #1
Opened 2022-07-30 00:02 UTC by jasonbyun8

wip hopefully can complete before I fly to Denmark

2022-08-24 19:24 UTC, amir-m2ai requested changes

2022-08-24 19:24 UTC, amir-m2ai commented on mir_navigation/launch/move_base_multi_agents.py
> +        agent_num (int): number of agent
Please put the type of variables in Typing of a function.

2022-08-24 19:24 UTC, amir-m2ai commented on mir_navigation/launch/move_base_multi_agents.py
>  def get_current_packages_status(get_world_properties):
Please add Typing to all functions.

2022-08-24 19:24 UTC, amir-m2ai commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
If any of PACKAGE_LENGTH, PACKAGE_WIDTH, NUM_PACKAGE_PER_ROW, NUM_PACKAGE_PER_COL, X_BUFFER, Y_BUFFER, X_INIT_BUFFER, Y_INIT_BUFFER, Z_LOCATION_BOX variables are not global variables, please use lowercase naming.

2022-08-24 21:20 UTC, jasonbyun8 commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
https://peps.python.org/pep-0008/

<img width="766" alt="Screen Shot 2022-08-24 at 2 18 31 PM" src="https://user-images.githubusercontent.com/3539047/186525559-f6a281ec-8915-4c10-ac0c-16caa42d37a5.png">

I was following pep8 convention please let me know if you still want me to change them

2022-08-24 21:36 UTC, jasonbyun8 commented on mir_navigation/launch/move_base_multi_agents.py
>  def get_current_packages_status(get_world_properties):
Done adding type hints

2022-08-24 21:37 UTC, jasonbyun8 commented on mir_navigation/launch/move_base_multi_agents.py
> +        agent_num (int): number of agent
I think you are seeing an old commit, can you please take a look the latest commit again?

2022-08-24 21:37 UTC, jasonbyun8 commented on mir_navigation/launch/move_base_multi_agents.py
>  def get_current_packages_status(get_world_properties):
Done adding type hints

2022-08-25 15:48 UTC, amir-m2ai commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
I thought we are following the Google Python Style [https://google.github.io/styleguide/pyguide.html].

2022-08-25 17:51 UTC, amir-m2ai commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
If I am not wrong, those are not a class names. I think if the style allows you to use capitalized naming, it would be good to be consistent in naming.

2022-08-25 20:15 UTC, jasonbyun8 commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
My bad, what I meant was this
<img width="783" alt="image" src="https://user-images.githubusercontent.com/3539047/186755388-b67c27b0-06cf-4c2b-bb09-6823f7216ea3.png">

Something similar has been found in the doc you provided here
<img width="980" alt="Screen Shot 2022-08-25 at 12 52 03 PM" src="https://user-images.githubusercontent.com/3539047/186757250-3d436f75-b4b5-4016-b1d8-86b923550bce.png">

I have been following the yapf linter + google style installed in vscode and the linter complained me using lower cases with those constants.

Also, we are not strictly following the google style, for example our character limit being 100 instead of 80. We might need to make a document about motion2ai style at some point.

I got your point though, I restructured the function so that we could avoid upper case issue.

2022-08-25 20:20 UTC, jasonbyun8 commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
Now I see what's happening, in the `if __name__ == "__main__"` global variables are being used; https://stackoverflow.com/questions/4775579/main-and-scoping-in-python

So I think what I was doing was correct. In anyways I restructured the file so there should be zero ambiguity now.

2022-08-26 17:22 UTC, wyattmotion2ai commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
Just FYI for the future. File level constants are meant to be in all caps, that is something that is expected to be used across the file. I would say it is also good for constants that are in the main runner as well. It is ok for how you had it @jasonbyun8, but in general that probably should have been an a configurable input from the command line (using argparse or something) or config. I understand why not though, it's kind of a pain to set it up.
  
If you have field in a class (`self.this_is_a_field = something`), that is considered a class variable or field and is in snake case
If you name a class `class ThisIsANormalizer: `, that should be in CapWords

2022-08-26 17:25 UTC, wyattmotion2ai commented on mir_navigation/launch/move_base_multi_agents.py
> +    packages_status_local = spawn_packages(loading_location_dict, num_of_boxes_loading_zones,
Also @jasonbyun8 @amir-m2ai 
https://www.notion.so/motion2ai/Coding-Style-Guide-395068c1b8324755ac885c04c72d056b#be6af6c1fbf74e0688633c74d44a3a52

2022-08-26 17:29 UTC, wyattmotion2ai commented on mir_navigation/launch/move_base_multi_agents.py
> +    return dock_locations, loading_locations, agent_locations
This type hint doesn't match, should this be` tuple[dict, dict, dict]`. You could even go deeper and do` tuple[dict[str, [tuple[float, float]]], dict[str, tuple[float, float]], dict[str. tuple[float, float]]`

2022-08-29 17:43 UTC, wyattmotion2ai commented
Honestly I think we are ok to merge, a lot of restructuring has been done on amir's branch and it was branched off of here

2022-08-29 18:29 UTC, jasonbyun8 commented on mir_navigation/launch/move_base_multi_agents.py
> +    return dock_locations, loading_locations, agent_locations
whoops, fixed it

2022-08-29 18:30 UTC, merged